// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace VueCore.Data.Entities
{
    public partial class AppSettingKey
    {
        public AppSettingKey()
        {
            AppSetting = new HashSet<AppSetting>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime UpdatedOn { get; set; }

        public virtual ICollection<AppSetting> AppSetting { get; set; }
    }
}