// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace VueCore.Data.Models
{
    public partial class AppSettingKeyModel
    {
        public AppSettingKeyModel()
        {
            AppSetting = new HashSet<AppSettingModel>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime UpdatedOn { get; set; }

        public virtual ICollection<AppSettingModel> AppSetting { get; set; }
    }
}