// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace VueCore.Data.Models
{
    public partial class AppSettingModel
    {
        public int Id { get; set; }
        public int AppSettingsKeyId { get; set; }
        public string Value { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime UpdatedOn { get; set; }

        public virtual AppSettingKeyModel AppSettingsKey { get; set; }
    }
}